### PR TITLE
Fix for rn0.50

### PR DESCRIPTION
**Pull request by jjmax75**
Hi, I was trying to run this on RN 0.50.4 and was having some problems.

I've fixed it to work with this version (and possibly any version >=0.48?)

I also added some linting rules. Great app and I plan to use it heavily, possibly extend it to.

Let me know if I can modify anything as I'm not sure if this will be backwards compatible.

### CODE REVIEW

**Comment by jondot** [comment]
Hi! wow, looks like we worked on this exactly the same time. Can you look at the current master and see if it works for you? 

PS - I prefer your solution since you took the time to also set up linting. So just see if the current solution in master is identical to yours (I use a more recent rxjs version - so if you can upgrade that would be nice. With that you should use 5.5.2, because the latest one has a critical regression)

**Comment by jjmax75** [comment]
Cool 😄 
The following doesn't work for me but other ones do
```
bars()(
  buffer()(
    events
  )
).subscribe;
```
There were also a couple more broken in the Readme

**Comment by jjmax75** [comment]
Thanks, will do.

This is a cool tool, we're experiencing some performance issues in an app here so the need to use this came up.

I'll push when I have RXJS updated

**Comment by jjmax75** [comment]
I'm also not sure about backwards compatibility, probably should be OK.

If a user is on RN<0.48 and updates React + RN will it work as the EventEmitter code in their app will be wrong?

If not, could we put a console error in there that's triggered if EventEmitter is incorrect?

**Comment by jjmax75** [comment]
I've Updated to RX5.2.2 and the following is the result-
The following is broken
```
bars()(buffer()(events).subscribe()); // events.do is not a function

bars(info => JSON.stringify(info.args).length)(
  filter({ method: 'createView' })(events)
).subscribe(); // subscribe of undefined

bars(info => JSON.stringify(info.args).length)(events).subscribe(); // subscribe of undefined
```

Following is working
```
filter({ method: 'createView' }, true)(events).subscribe();

filter({ type: Snoopy.TO_NATIVE }, true)(events).subscribe();
```

Not sure what's causing the issue there, looks like the events object isn't being populated?

**Comment by jondot** [comment]
cool, so i'll revert my change and merge yours

**Comment by jondot** [comment]
@jjmax75 strange, so using 5.2.2 as opposed to the 5.0 beta leaves part of the flows broken?

**Comment by jjmax75** [comment]
yeah, only on my version though, most work on yours but I can't be 100% about that either - limited testing.

I don't see any real difference between the way we're importing RXJS.

Your version uses
`import Rx from 'rxjs/Rx'`
then
`this.events = Rx.Observable.fromEvent(emitter, 'mqspy')`

Mine uses - 
```
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/fromEvent';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/bufferTime';
```
then
`this.events = Observable.fromEvent(emitter, 'mqspy');`

I have no experience with RXJS but from reading up on it this should work.

**Comment by jondot** [comment]
So i worked based on your pull request and pushed into a branch here. I had to restore the bar graph and tweak the example module dependency but otherwise all the rest is your changes.

https://github.com/jondot/rn-snoopy/tree/jmax75-fixForRN0.50

Can you test that out? For me it all works

**Comment by jjmax75** [comment]
Just checked this, works perfectly 😄 

I'll have a look at the code but why was the bars streamer not working?

This package has been a great way for our team to get an idea of where performance issues might be occurring and to get us all focused on resolving them. Thanks. I hope to be able to contribute more. If there's any future dev you have planned and would like help with it I'm interested.

**Comment by jondot** [comment]
Awesome stuff. I'm not sure what happened with the bar thing, but it felt like some kind of debugging code that was left over.
Very happy to hear it helps. I'm a strong believer in Karma so definitely good to hear 👍 

In terms of roadmap, I wanted this to be very low-level so that people could build their own "patterns" of detectors.

But the next step was always to have a library of these recipes built-in. 
Think of it like "ESlint for react native messagebus".

For example:

* Detecting heavy calls `NoHeavyFunctionCallDetector(..)`
* Detecting heavy UIs (by tracing calls for creation and positioning of elements) `NoHeavyUIWork(..)`

And then people can define rules:

```
{ rules: {
    "no-heavy-function-calls": "warning",
    ...
   }
}
```

And so on. 

It's still brain-storming material, but I would be happy if you wanted to take a lead on how this should look and work. Count me in if you need some spare hands to make it happen!

**Comment by jondot** [comment]
Back to the PR - I should merge `jmax75-fixForRN0.50` as opposed to this one, yes?

**Comment by jjmax75** [comment]
Yes on the merge, works great

That sounds really interesting about it being the ESlint of RN messagebus. From our own experience its core to our values that performance is always at the forefront. With a tool like this running automated tests then it would be a great way to keep everyone focused on that.

I have some work to do on our app today but I'll get back in touch next week about working with you on this if you like.

**Comment by jondot** [comment]
Cool, so i will 
1. close this PR
2. merge the other branch
3. document discussion here in a new ticket in issues
4. cut a new release and push to NPM.

Thanks for all the great work!

**Pull request merged**
